/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include <sstream>
#include "libB.h"
#include "libA.h"
#include "libA-version.h"

std::string libB::describe() {
    std::ostringstream oss;
    oss << "libB compiled against libA " << LIBA_VERSION << std::endl;
    oss << "libB runs against libA " << libA::version();
    return oss.str();
}
