/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LIBA_H
#define LIBA_H

#ifdef _WIN32
#define LIBA_EXPORT_FUNC __declspec(dllexport)
#else
#define LIBA_EXPORT_FUNC
#endif

#include <string>

namespace libA {
    std::string LIBA_EXPORT_FUNC version();
}

#endif
