/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "libA.h"
#include "libA-version.h"
#include "libB.h"

int main () {
    std::cout << "app compile against libA " << LIBA_VERSION << std::endl;
    std::cout << "app runs against libA " << libA::version() << std::endl;
    std::cout << libB::describe() << std::endl;
    return 0;
}
