/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LIBB_H
#define LIBB_H

#ifdef _WIN32
#define LIBB_EXPORT_FUNC __declspec(dllexport)
#else
#define LIBB_EXPORT_FUNC
#endif

#include <string>

namespace libB {
    std::string LIBB_EXPORT_FUNC describe();
}

#endif
